set(_CATKIN_CURRENT_PACKAGE "clustering")
set(clustering_VERSION "0.0.0")
set(clustering_MAINTAINER "jeongwoooh <jeongwoooh@todo.todo>")
set(clustering_PACKAGE_FORMAT "2")
set(clustering_BUILD_DEPENDS "roscpp" "rospy" "std_msgs" "geometry_msgs" "message_generation")
set(clustering_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs" "geometry_msgs")
set(clustering_BUILDTOOL_DEPENDS "catkin")
set(clustering_BUILDTOOL_EXPORT_DEPENDS )
set(clustering_EXEC_DEPENDS "roscpp" "rospy" "std_msgs" "geometry_msgs" "message_runtime")
set(clustering_RUN_DEPENDS "roscpp" "rospy" "std_msgs" "geometry_msgs" "message_runtime")
set(clustering_TEST_DEPENDS )
set(clustering_DOC_DEPENDS )
set(clustering_URL_WEBSITE "")
set(clustering_URL_BUGTRACKER "")
set(clustering_URL_REPOSITORY "")
set(clustering_DEPRECATED "")