// Generated by gencpp from file localization/Keyop.msg
// DO NOT EDIT!


#ifndef LOCALIZATION_MESSAGE_KEYOP_H
#define LOCALIZATION_MESSAGE_KEYOP_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace localization
{
template <class ContainerAllocator>
struct Keyop_
{
  typedef Keyop_<ContainerAllocator> Type;

  Keyop_()
    : header()
    , key(0)  {
    }
  Keyop_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , key(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int32_t _key_type;
  _key_type key;





  typedef boost::shared_ptr< ::localization::Keyop_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::localization::Keyop_<ContainerAllocator> const> ConstPtr;

}; // struct Keyop_

typedef ::localization::Keyop_<std::allocator<void> > Keyop;

typedef boost::shared_ptr< ::localization::Keyop > KeyopPtr;
typedef boost::shared_ptr< ::localization::Keyop const> KeyopConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::localization::Keyop_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::localization::Keyop_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::localization::Keyop_<ContainerAllocator1> & lhs, const ::localization::Keyop_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.key == rhs.key;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::localization::Keyop_<ContainerAllocator1> & lhs, const ::localization::Keyop_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace localization

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::localization::Keyop_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::localization::Keyop_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::localization::Keyop_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::localization::Keyop_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::localization::Keyop_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::localization::Keyop_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::localization::Keyop_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b541b7ffb470da46407f12a133fc3e51";
  }

  static const char* value(const ::localization::Keyop_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb541b7ffb470da46ULL;
  static const uint64_t static_value2 = 0x407f12a133fc3e51ULL;
};

template<class ContainerAllocator>
struct DataType< ::localization::Keyop_<ContainerAllocator> >
{
  static const char* value()
  {
    return "localization/Keyop";
  }

  static const char* value(const ::localization::Keyop_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::localization::Keyop_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"int32 key\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::localization::Keyop_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::localization::Keyop_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.key);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Keyop_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::localization::Keyop_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::localization::Keyop_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "key: ";
    Printer<int32_t>::stream(s, indent + "  ", v.key);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LOCALIZATION_MESSAGE_KEYOP_H
